# MIT License
# Copyright (c) 2022 Ryan Gorzek
# https://github.com/gorzek-ryan/ecephys_viz/blob/main/LICENSE
# https://opensource.org/licenses/MIT

[build-system]
requires = [
    "setuptools>=61.2.0",
    "wheel"
]
build-backend = "setuptools.build_meta"
